baseURL: 'http://example.org/'
languageCode: en-us
title: Mark Stuart | Github IO
theme: Hucore
copyright: >-
  &copy; 2017 | <a href="https://github.com/mgjohansen/hucore.git"
  target="_blank">Hucore theme</a> & <a href="http://gohugo.io"
  target="_blank">Hugo</a> ♥
contentDir: "content"
publishDir: "docs"
taxonomies:
  tag: tags
  category: categories
params:
  description: Mark Stuart's Github IO pages
  keywords:
    - keyword 1
    - keyword 2
    - keyword 3
  author: Mark Stuart
  sharingicons: true
  highlight:
    style: github
    languages:
      - go
      - dockerfile
  social:
    - url: 'https://github.com/stuarmark'
      fa_icon: fa-github
    - url: 'https://www.linkedin.com/in/mark-stuart-877143a/'
      fa_icon: fa-linkedin-square
